openapi: 3.0.1
info:
  title: Mascota Microservice Endpoints
  description: Definición de los endpoints de Mascota service para la app
  contact:
    name: UNAM
    url: https://www.unam.mx/
    email: elocasodelosidolos@gmail.com.mx
  version: v1.0
servers:
- url: http://localhost:8084
  description: URL del servidor para los servicios con puerto
tags:
- name: mascota
  description: API del recurso Mascota
paths:
  /api/mascotas/{id}:
    get:
      tags:
      - mascota
      summary: Busca mascota por id y lo regresa
      description: Busca mascota por id y lo regresa en un json
      operationId: mascotaPorId
      parameters:
      - name: id
        in: path
        description: Id del mascota a retornar
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Mascota encontrada exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mascota'
        '404':
          description: El id de la mascota no fue encontrado
    put:
      tags:
      - mascota
      summary: Actualiza un mascota por id
      description: Actualiza un mascota pot id con los datos del json
      operationId: actualizarMascota
      parameters:
      - name: id
        in: path
        description: Id del mascota a ser actualizado
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Mascota'
        required: true
      responses:
        "200":
          description: Mascota actualizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mascota'
        '404':
          description: Mascota no encontrado y no actualizado
    delete:
      tags:
      - mascota
      summary: Elimina un mascota por id
      description: Elimina un mascota pot id y regresa un No Content
      operationId: eliminarMascota
      parameters:
      - name: id
        in: path
        description: Id del mascota a ser eliminado
        required: true
        schema:
          type: string
      responses:
        "204":
          description: No Content
  /api/mascotas:
    get:
      tags:
      - mascota
      summary: Obtiene la lista de mascotas
      description: Regresa un json con todos las mascotas
      operationId: obtenerMascotas
      responses:
        "201":
          description: Arreglo json de las mascotas encontradas encontrados
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Mascota'
    post:
      tags:
      - mascota
      summary: Crear mascota
      description: Crea un mascota
      operationId: crearMascota
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Mascota'
        required: true
      responses:
        "201":
          description: Mascota creado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mascota'
        "409":
          description: Ya existe un Mascota con el nombre especificado
          
components:
  schemas:
    Mascota:
      type: object
      properties:
        id:
          type: string
        nombre:
          type: string
