apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: tekton-trigger-binding
spec:
  params:
  - name: giturl
    value: https://github.com/luis-cdmx/diplo-cloud-mascota-service
  - name: maven_image
    value: gcr.io/cloud-builders/mvn@sha256:8f38a2667125a8d83f6e1997847fedb6a06f041c90e2244884153d85d95f869b
  - name: buildah_image
    value: docker.io/luisriveracdmx/mascota-rest-app:1.0
  - name: mascota-rest-manifest
    value: https://raw.githubusercontent.com/luis-cdmx/diplo-cloud-mascota-service/main/resources/manifest/mascota-rest.yaml
