apiVersion: apps/v1
kind: Deployment
metadata:
  name: mascota-mongo-deployment
  labels:
    app: mascota-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mascota-mongo
  template:
    metadata:
      labels:
        app: mascota-mongo
    spec:
      containers:
        - name: mongo
          image: mongo
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mascota-mongo-service
spec:
  selector:
    app: mascota-mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  internalTrafficPolicy: Local
