apiVersion: apps/v1
kind: Deployment
metadata:
  name: mascota-rest-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mascota-rest
  template:
    metadata:
      labels:
        app: mascota-rest
    spec:
      containers:
        - name: mascota-rest-container
          image: luisriveracdmx/mascota-rest-app:latest
          ports:
            - containerPort: 8084
